services:
  wordpress:
      image: wordpress
      links:
      - mariadb:mysql
      environment:
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=root
      ports:
      - 8080:80
      volumes:
      - ./html:/var/www/html
  mariadb:
      image: mariadb:10.6.4-focal
      environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      volumes:
      - ./database:/var/lib/mysql